### ISSUE TITLE
is it possible to disable all dates

### ISSUE THREAD

**Issue by feldmarv** [KennethanCeyer/PIGNOSE-Calendar#1]
is it possible to disable all days by default and then enable an array of days?

**Comment by KennethanCeyer** [comment]
Hello @feldmarv!

Thank you for asking.


No we have not allowed date range picker features yet.

But i can update with in this week.

Cloud you please tell me specific specs that you want to use?

Sorry about the sentence!


And if you have any questions, please send me any format. I will reply as soon as possible.

Thank you

**Comment by feldmarv** [comment]
@KennethanCeyer 
Thanks for your fast answer.
What we need is not exactely a date range picker. We just want to disable all days bi a default (should be a setting). Disabled means its not clickable on UI and is marked as disabled. Then we load an array of dates (days). This dates should then be clickable.

Thanks in advance

**Comment by KennethanCeyer** [comment]
Hi @feldmarv,

I think i can make for your needs.

The update may will be on Oct 21 or 22.

I am sorry but, Please waiting few days for updating.

Thank you for your time 👍

**Comment by feldmarv** [comment]
@KennethanCeyer 
Thanks this sounds nice! Can you assure that its ready by the end of the week? Because i need to create some implementation.

**Comment by KennethanCeyer** [comment]
Yes sure, maybe i will be working on next day.

**Comment by KennethanCeyer** [comment]
Hi @feldmarv 

I have updated for your feature `disabled dates`.

You can check the feature on [Demo site](http://www.pigno.se/barn/PIGNOSE-Calendar/)

You can use this feature by download v1.2.9 version.

Thank you.

**Comment by feldmarv** [comment]
@KennethanCeyer 
Wow thanks that looks cool!
So how to disable all dates by default. Is there an option called: disabledDates: true, and then enableDates: [2016-01-03, 2016-01-04] that will for example only enable this two dates?

**Comment by feldmarv** [comment]
As I see the options
toggle: true,
reverse: true,
does disable the whole calendar which is great, but dates are still clickable. And how to enable now an array of dates?

thanks in advance

**Comment by KennethanCeyer** [comment]
@feldmarv 

OMG I think i don't understand your needs.

I will make `displayDates` and `readonly` specs today.

I think you want to display only readable dates, is it correct?

Thank you for your time :)

**Comment by feldmarv** [comment]
@KennethanCeyer 
Thanks a lot for your answer.
Yes, on the calendar disabled dates are visible but not accessible (grey font). Enables dates are accessible and font is green.

**Comment by KennethanCeyer** [comment]
Hi @feldmarv 

I have updated [`1.2.11` version](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.2.11)

`enabledDates` option is date array format like `disabledDates`.

This option makes all dates to disabled state and

only declared item in enabledDates will be enabled state (clickable date).

Thank you

**Comment by feldmarv** [comment]
GREAT! This really is our Usecase!

One question: I load activeDays via ajax. Then the calendar just is empty. If  I try to load the exact data without ajax directly hardcoded its working. Do we need a setter method maybe setEnabledDay. Or is there just an issue with loading order?

var activeDays = [];
  $.ajax({
                url: 'xyz',
                dataType: 'json',
                method: "get",
                async: false,
                cache: false,
                success: function (data) {
                    $.each(data.dates, function (i, d) {
                        var date = new Date(d).toISOString().slice(0, 10);
                        activeDays.push(date);
                    });
                }
            });

$('#datetimepicker').pignoseCalendar({
select: getFreeAppointments,
enabledDates: [activeDays]
});

**Comment by KennethanCeyer** [comment]
I think you must to use like the snippet. 

```javascript
$('#datetimepicker').pignoseCalendar({
    select: getFreeAppointments,
    enabledDates: activeDays // It be changed. 
});
```

**Comment by feldmarv** [comment]
true thanks! such this small typo.
Thanks for your GREAT work!

**Comment by abbu1** [comment]
I want to pass array of collection of dates to disabled when i press button how we can do in ngxbootstrap?

Thanks in advance

**Comment by mprince2k18** [comment]
here I solved in this way:

`$init_date = new Date();`

 `$current_date = $init_date.getFullYear() + '-' + ($init_date.getMonth() + 1) + '-' + $init_date.getDate();`

`$('.pig_calendar').pignoseCalendar({
      minDate: $current_date
  });`
