### ISSUE TITLE
When enabling 'multiple' property for my Calendar as I assigned it to a textbox, it returns null when selecting a single date.., and next it goes stuck entire browser. May I did something wrong with it??

### ISSUE THREAD

**Issue by daranaveen007** [KennethanCeyer/PIGNOSE-Calendar#10]

**Comment by KennethanCeyer** [comment]
Hi @daranaveen007 

First of all, I do not understand what you mean is exactly.

When you use `multiple` option in your calendar. You can select two specific dates.

But in the first selection, I think the second one will be returned null.

I need the error logs when you gone stuck for solve this issue, Would you send the logs message to me?

**Comment by daranaveen007** [comment]
Sorry dear @KennethanCeyer sir.. I did not get any error logs like that.. But i'll send you the screens. I'm just stuck there when happen that.

**Comment by KennethanCeyer** [comment]
Okay @daranaveen007 

Where can i see your screenshot?

I will fix immediately your problem as possible as i can.

**Comment by daranaveen007** [comment]
You cam find it here:
[https://postimg.org/image/b56x2yazz/](url)

**Comment by daranaveen007** [comment]
video here:
https://youtu.be/kR-qWwWPc08

**Comment by KennethanCeyer** [comment]
Hi @daranaveen007 🍵 

Thank you for sending to me the detail attached files.

I observe the phenomenon that you said

I will fix now, That issue

**Comment by KennethanCeyer** [comment]
This is has been solved at [v1.3.1 version](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.3.1).

Thank you for reporting.

I can fix because your active reporting.

**Comment by KennethanCeyer** [comment]
The new version are released [v1.3.2](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.3.2).

v1.3.2 version are reflected the issue #11.

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
