### ISSUE TITLE
Past Dates to Grey Out-Bug

### ISSUE THREAD

**Issue by snapp33** [KennethanCeyer/PIGNOSE-Calendar#12]
Hello Kennethan,
I noticed on the Disabled Range Calendar even on your page demo example that even though today is Nov 12, you are still able to go back to Nov 9, see for yourself http://www.pigno.se/barn/PIGNOSE-Calendar/

Thanks!

**Comment by snapp33** [comment]
Strange just see it today Nov 13 and it is correct, not sure if you fixed it

**Comment by KennethanCeyer** [comment]
Hi @snapp33 
And thank you for sending a report to me

I'm sorry but,

I can't understand what is happening exactly.

I guess, When you see even on PIGNOSE-Calendar example in the public plugin site.

And today Nov 12(But this date is in disabled date range), show you can't control them and use only pick Nov 9 Right?

Recently, i fix today date bugs on disabled date range, If today date is in disabled date range, It will be turned off 😄

**Comment by snapp33** [comment]
Hi Kennethan, I did save an image   ##below on Nov 11 that shows that I was able to go back to Nov 9 and Nov 10.
I will contine to check this week if it happens again. Thanks!

![pignose calendar 111116](https://cloud.githubusercontent.com/assets/23240361/20251751/6de7db10-a9e1-11e6-9c8d-a940eebc1686.jpg)

**Comment by KennethanCeyer** [comment]
Hi @snapp33 😄 

Yes i think this logic has something problem about moment usage.

I fix this snippets, (This snippets is example for using `minDate` and `maxDate`.

Two options must be `2 day`, `25 day` each of options.

Thank you for reporting to me.

It was helpful 👍 

PS) This issue are solved at `v1.3.5` version.
