### ISSUE TITLE
how to untoggle date

### ISSUE THREAD

**Issue by feldmarv** [KennethanCeyer/PIGNOSE-Calendar#13]
For example 28th is toggled, after toggling on the 30th the 28th should be untoggled. How to accomplish this usecase?

![bildschirmfoto 2016-11-16 um 08 09 43](https://cloud.githubusercontent.com/assets/9105618/20337886/0c984832-abd4-11e6-8f64-51468f5b793f.png)

**Comment by KennethanCeyer** [comment]
Hi @feldmarv :)

Sorry about late 😢 

This issue `need snippets`...

If you okay, Please tell me more specific detail

Thank you for your time 👍

**Comment by feldmarv** [comment]
Thanks for the reply.
I do load certain events in Array then display it in the calendar.
var slotDates = [];
 var url = "../../../events/getSlotDates/" + getCookie("eventId");
    $.ajax({
        method: "get",
        url: url,
        dataType: 'json',
        cache: false,
        async: false,
        success: function (data) {
            $.each(data.slotDates, function (i, d) {
                slotDates.push(d);
            });

        }
    });

$('#terminslot-kalender').pignoseCalendar({
        lang: 'de',
        toggle: true,
        enabledDates: slotDates,
        date:moment(slotDates[0]),
        select: loadSlotsbyDate
    });

_______________

As you can see when an event in the calendar is selected it loads specific information about this event by the function loadSlotsbyDate(), The toggled event is marked as active. If the user toggles an other event this information is loaded by loadSlotsbyDate(). Now the problem is that both dates are active even if only information about one is displayed.

![bildschirmfoto 2016-11-25 um 14 10 56](https://cloud.githubusercontent.com/assets/9105618/20626286/02e82d06-b319-11e6-881b-73537cabc89f.png)

**Comment by KennethanCeyer** [comment]
I didn't think in async connection calling styles @feldmarv 

In your code,

`success` callback will be executed after Calendar initialized.

And `select`, `set` method in `PIGNOSE Calendar` seems need be fixed.

I will check an updates about this issue.

- `set`, `select` method duplication problem.
- `async connection date update` method.

**Comment by feldmarv** [comment]
was able to fix it by just remove this line ` toggle: true`

**Comment by KennethanCeyer** [comment]
Sorry @feldmarv 

I be late for checking the issue.

I think i could answer the issue at tonight 😄

**Comment by KennethanCeyer** [comment]
Okay this sounds good to me 👍 

Toggle option is making calendar date button to toggle button.

If you disable toggle option,

Calendar will be ordinary calendar.

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
