### ISSUE TITLE
Setting range and new language.

### ISSUE THREAD

**Issue by TNDecoder** [KennethanCeyer/PIGNOSE-Calendar#14]
I would like an option to set a range of days to pick at once.

eg...

if you pick 2016-11-22 it'll automatically set the range to look like:
(5 days ahead): 2016-11-22 ~ 2016-11-27

so the people using the calendar don't have to pick two dates.

:: i've for my need added a new language to the plugin (da - Danish):
```javascript
	var languagePack = {
		supports: ['en', 'ko', 'fr', 'ch', 'de', 'jp', 'pt', "da"],
		weeks: {
			en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
			ko: ['일', '월', '화', '수', '목', '금', '토'],
			fr: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],
			ch: ['日', '月', '火', '水', '木', '金', '土'],
			de: ['SO', 'MO', 'DI', 'MI', 'DO', 'FR', 'SA'],
			jp: ['日', '月', '火', '水', '木', '金', '土'],
			pt: ['Dom','Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
			da: ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'],
		},
		monthsLong: {
			en: ['January', 'February', 'March', 'April', 'May', 'Jun', 'July', 'August', 'September', 'October', 'November', 'December'],
			ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
			fr: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
			ch: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
			de: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
			jp: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
			pt: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
			da: ['Januar', 'Februar', 'Marts', 'April', 'Maj', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'December'],
		},
		months: {
			en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
			fr: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin', 'Juil', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
			ch: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
			de: ['Jän', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
			jp: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
 			pt: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
			da: ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
		}
	};
```

**Comment by KennethanCeyer** [comment]
Hi @TNDecoder 

I agree to add that feature you said.

But i think the range of week option(Mon ~ Sun or Sat ~ Sun) is a little bit difficult some other people...

So this discussion may must be clarified more than.

----

Thank you for contribution :)

It is very useful for me 👍 

But the update will be progressed tonight,

If update is completed, I will reply on this issue!

**Comment by KennethanCeyer** [comment]
Hi @TNDecoder again.

Danish language updated on new version [v1.3.8](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.3.8)

Thank you for your contribution~! 👍

**Comment by TNDecoder** [comment]
And by the way: the feature i wished was like:

Rangelength:5

And then it choose 5 days ahead. Or

Rangelength:2

And then it choose 2days ahead

I don't know if that makes it easier

**Comment by KennethanCeyer** [comment]
Hi @TNDecoder 

At the point, I think this isn't be good structure.

I will think about making this than more easier and properly.

**Comment by TNDecoder** [comment]
Then i'll work on a go-around with the select method.

**Comment by KennethanCeyer** [comment]
Hi @TNDecoder again.

For first step,

I added the new feature `pickWeeks` option.

This option helps you to click the weeks by single picking.

Check the feature at [this page](http://www.pigno.se/barn/PIGNOSE-Calendar/#pick-weeks).

Note: This option support from [`v1.3.9`](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.3.9).

Thank you 😄

**Comment by TNDecoder** [comment]
No, thank you! That's exactly what i was looking for!

**Comment by KennethanCeyer** [comment]
Good 👍 

Well, This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
