### ISSUE TITLE
Local Time Calendar Glitch

### ISSUE THREAD

**Issue by snapp33** [KennethanCeyer/PIGNOSE-Calendar#15]
Hello Kennethan,
I noticed in our local time in the evening that the default date (blue circle day) would change to the next day even though it is still the 23rd today, not sure if it is a timezone issue but wanted to bring to your attention.
It shouldn't change until midnight.
![timezone glitch calendar](https://cloud.githubusercontent.com/assets/23240361/20585184/c43bfe76-b1be-11e6-8d1c-01703768f219.jpg)

**Comment by KennethanCeyer** [comment]
Hi @snapp33 

Wow.. It seems to be weird situation...

I will check this after work :)

Thank you !

**Comment by KennethanCeyer** [comment]
Hi again @snapp33.

I am searched the issue what you said,

But today is working on `moment library`.

Calendar gets today by `moment()` function.

So we need more details about this.

If you find same error,  Please add more information(plugin version, country etc) if you okay

Thank you for your interest 😄

**Comment by snapp33** [comment]
Just looked at it now (USA, Central Time 816am) and it is correct for today but it happens later in evening, not sure the exact time but I checked it my time 7pm is when this occurs so another 11 more hours time (using 1.3.7), hope that helps....thanks!

**Comment by KennethanCeyer** [comment]
Umm.. I think it is `intermittent issue`.

In my perspective, This error hasn't occurred still now...

If you get same issue,

Please see a date on [Here](http://www.nhpcw.com/upload/sample_moment_112416112511.jpg).

You can see the last one at Format Dates section like follows.

![sample](http://www.nhpcw.com/upload/sample_moment_112416112511.jpg)

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
