### ISSUE TITLE
wrong days position french

### ISSUE THREAD

**Issue by nono88100** [KennethanCeyer/PIGNOSE-Calendar#16]
Hello Kennethan

I'm a French developer and I use your calendar and I like it but their is a problem.
When the language of the calendar is set on 'fr' for French the first day is 'Lundi' but on the other language the first day is 'Sunday'.
Here is the French version
![firefox_2016-11-29_11-52-31](https://cloud.githubusercontent.com/assets/24246388/20707119/9464695c-b62a-11e6-9e36-7bc0a339e80f.png)

Here is the English version
![firefox_2016-11-29_11-56-37](https://cloud.githubusercontent.com/assets/24246388/20707240/ec103000-b62a-11e6-9c20-31212472e5f3.png)

Has you can see with the French version all days are shifted by one day.

I found a solution of this issue if you want to correct the original script.
On the file pignose.calendar.js,
you need to change on line 184 the line :
`fr: ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'],`

to the line :
`fr: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],`

It would be great to add a function to choose the first day of the calendar if you have time :)

Thank you for your tool you help me a lot !

**Comment by KennethanCeyer** [comment]
Hi @nono88100 

Sorry about the mistake... I think you so inconvenient for use the plugin.

I will update right now new version `v1.3.9` this version is updated for French languages.

**Comment by KennethanCeyer** [comment]
Now you can see the new version `v1.3.9` [at here](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.3.9)

In this version, The issue are solved and updated 😄

**Comment by nono88100** [comment]
Thank you ! :)

**Comment by ParaNaud** [comment]
Hello, 
I downloaded v1.4.0, used 'fr" language but DIM is still the first day of the week.
I was looking for a way to set the "fisrtdayoftheweek" to monday.
Thanks in advance.
