### ISSUE TITLE
Refresh Calendar Not working

### ISSUE THREAD

**Issue by emnkaror** [KennethanCeyer/PIGNOSE-Calendar#17]
Hi, 
I have a ticket form where i am using the depart and return dates, i have two datepickers, when first change it cause the min date change to 2nd. I am using in select function and in apply function but it is not changing the dates in 2nd. 
When change event call then i set new date limits and call like this.
var $btn2 = jq("#txtReturnDate").pignoseCalendar({
        modal: true,
        minDate: finaldate,
        maxDate: maxDate,
        select: function (date) {
            $btn2.text(date);
        }
    });

**Comment by KennethanCeyer** [comment]
Sorry @feldmarv 

I be late for checking the issue.

I think i could answer the issue at tonight 😄
