### ISSUE TITLE
Enable date

### ISSUE THREAD

**Issue by shivanitak** [KennethanCeyer/PIGNOSE-Calendar#18]
How to add enabledDates feature in place of disabledDatesin jquery code??

**Comment by KennethanCeyer** [comment]
Sorry @feldmarv 

I be late for checking the issue.

I think i could answer the issue at tonight 😄

**Comment by KennethanCeyer** [comment]
I need more specific details.

When you use `enabledDates` `disabledDates` either,

What is your expected scenario?

(ex: enabledDates must be overrided disabledDates.)

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
