### ISSUE TITLE
Current date selection issue !!

### ISSUE THREAD

**Issue by devmike1992** [KennethanCeyer/PIGNOSE-Calendar#19]
current date is not selected in single mouse click and date value is not coming into the array.. 

please help!!

**Comment by KennethanCeyer** [comment]
Sorry @feldmarv 

I be late for checking the issue.

I think i could answer the issue at tonight 😄

**Comment by KennethanCeyer** [comment]
I think you can fix this issue for changing `initialized` option to `false`.

If you have some issue, Even try this solution

Please send me another issue below.

**Comment by devmike1992** [comment]
https://github.com/KennethanCeyer/PIGNOSE-Calendar/issues/2

please check this link...

**Comment by devmike1992** [comment]
i'm still facing this issue !!

**Comment by devmike1992** [comment]
![pignose calendar problem fix i need](https://cloud.githubusercontent.com/assets/24837801/21710286/aba7f48e-d40d-11e6-9670-59d2c60e9f78.png)

THIS IS THE OUTPUT I NEED WHEN I CLICK ON TODAY'S DATE.. AND IT SHOULD BE LIKE THIS ON A SINGLE CLICK !! FIRST MOUSE CLICK !!

**Comment by KennethanCeyer** [comment]
Ah!

I see what exactly you want.

This seem bugs at `toggleDates`, I am very sorry about that.

This issue will be fetched within six hour.

And when it is done, I will notice at this issue.

Thank you @devmike1992.

**Comment by KennethanCeyer** [comment]
This issue seem solved at **v1.4.0** version.

If you have same error at this version.

Please resend new issue 🍺

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
