### ISSUE TITLE
Bug: Actual date on click return null

### ISSUE THREAD

**Issue by matheusdelima** [KennethanCeyer/PIGNOSE-Calendar#2]
I'm working in a project and i found a problem.
When i click in date of today is return null, however when i click again its work.

**Comment by KennethanCeyer** [comment]
Hi @matheusdelima 

Ahh.. I don't expect that

I will fix this issue today :)

 Thank you for reporting us!

**Comment by KennethanCeyer** [comment]
Hi @matheusdelima again

I have fixed the bugs that you told me.

Please check [demo page](http://www.pigno.se/barn/PIGNOSE-Calendar/)

If you get first click to today, You can get today date and that button does not disabled even enabled state.

Thank you

**Comment by KennethanCeyer** [comment]
This issue will be closed after 3 days.

If you have other problem,

Please add new issue.

Thank you :)

**Comment by matheusdelima** [comment]
Thank you :)
Great Work, Congratulations!

**Comment by devmike1992** [comment]
When I click on  today's date, it returns null.. ( [ ] Array is empty.. and that button doesn't even enabled state)
however when I click again its work..

**Comment by devmike1992** [comment]
Can you please send me the codes for fixing this issue !!

**Comment by devmike1992** [comment]
![pignose calendar 2016-12-30 1fff2-49-42](https://cloud.githubusercontent.com/assets/24837801/21561124/82c1248e-ce8e-11e6-85cb-277f516a64cd.png)



When I 1st click on today's date it should look like in the picture..!!

**Comment by KennethanCeyer** [comment]
This issue is already closed, so the answer will be added at #19.

Thank you 👍
