### ISSUE TITLE
DateFormat to View before Pignose Calendar

### ISSUE THREAD

**Issue by snapp33** [KennethanCeyer/PIGNOSE-Calendar#20]
Hello Kennethan,
Not sure if this is your scope of work but our current calendar format before it goes to Pignose shows the date as MMDDYY but I want it to show as DAYOFWEEK,MONTH,DATE,YEAR so that way it is universal and not confuse Europe/Asia date format
![dateformat011717](https://cloud.githubusercontent.com/assets/23240361/22024325/38575b20-dc8f-11e6-8d68-0259c241d288.jpg)
Hope you can advice how best to see something like this before it goes to Pignose Calendar

Thanks

**Comment by KennethanCeyer** [comment]
Hi there! @snapp33 

PIGNOSE Calendar supports `moment` library and that format patterns.

If you want to set custom date format for input element.

Just follow the snippets:

```javascript
$('input.some-input-element').pignoseCalendar({
// This code will be working at INPUT type element nodes.
    format: 'ddd, MMM DD, YYYY'
   // 2017-02-02 -> Thu,Feb 02, 2017
});
```

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
