### ISSUE TITLE
 languagePack chinese

### ISSUE THREAD

**Issue by maxma51** [KennethanCeyer/PIGNOSE-Calendar#21]
pignose.calendar.js

 weeks:
ch: ['日', '一', '二', '三', '四', '五', '六'],

monthsLong:
ch: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],

months: 
ch: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],

**Comment by KennethanCeyer** [comment]
Ah! Thank you @maxma51 

I could don't know forever what is wrong

If you don't mention it!!

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
