### ISSUE TITLE
Enable Support for ES

### ISSUE THREAD

**Issue by adrian2monk** [KennethanCeyer/PIGNOSE-Calendar#22]
Added support for Spanish language in my [Fork](https://github.com/adrian2monk/PIGNOSE-Calendar.git)

**Comment by KennethanCeyer** [comment]
Thank you for your contribution on this project @adrian2monk 

I am very appreciate.

I hope this project and other open source project to open for contributors.

//

By the way

This feature will be updated at **v1.4.1**

**Comment by adrian2monk** [comment]
I'm glad to help

**Comment by KennethanCeyer** [comment]
This issue are related #27

I'm very appreciated for your contribution 👍
