### ISSUE TITLE
How to get the selected date pls help!

### ISSUE THREAD

**Issue by galoncyryll** [KennethanCeyer/PIGNOSE-Calendar#23]
Hi im a newbie of javascript, we have a project in capstone that needs an appointment scheduler and i am using this calendar as the datepicker but i dont know how to get the value selected. Pls help asap! thanks :)

**Comment by KennethanCeyer** [comment]
Hello @galoncyryll 

Sorry, I am late...

If you get selected value when user select some date.

You can use `select` callback at the option.

See the follows:

```javascript
$('.calendar-dark').pignoseCalendar({
	theme: 'dark', // light, dark
	select: function(date) {
           console.log('your first date', date[0]);
           console.log('your sencond date', date[1]);
        }
});
```

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
