### ISSUE TITLE
PL strings

### ISSUE THREAD

**Issue by pkly** [KennethanCeyer/PIGNOSE-Calendar#24]
Weekdays
pl: ['Nie', 'Pon', 'Wto', 'Śro', 'Czw', 'Pią', 'Sob']
Months long
pl: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień']
Months short
pl: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru']

No point in making a pull request for something so minor.
Great work on the plugin btw, it's superb.

**Comment by KennethanCeyer** [comment]
Thank you @pkly 

I will update this language pack on today.

This will be fetched *v1.4.1*!
