### ISSUE TITLE
Date range selection can pass through disabled dates

### ISSUE THREAD

**Issue by pkly** [KennethanCeyer/PIGNOSE-Calendar#25]
I have a bunch of dates and use them to disable specific ranges in the calender. I use the same calender for selection, but it's possible to select "over" the disabled dates.

for example:
disabled range: 2017-01-10 to 2017-01-15
date start: 2017-01-05
date end: 2017-01-20

it's possible to select that in the first place -> not the greatest when it comes to usability.

**Comment by TNDecoder** [comment]
If people selects above the selected dates they're really stupid however this would require remodeling of the reservation system in this plugin..

I would advice you to check the dates in php and throw an form error if they overlap (you'll have to do this anyway)

**Comment by pkly** [comment]
Well of course I do check it in php and throw errors and such, but my point is:

if anyone's trying to select a date that overlaps with a disabled date in any way, the calender shouldn't allow them to do that.

I'd suggest the following:

Disabled ranges: [.., .., 2017-01-10 to 2017-01-15, .., ..]
First selected date: 2017-01-05
Second selected date: 2017-01-20

Currently it'll select the dates, overlapping the disabled date
Why not just make the selection date shorter? 
Instead of selecting the whole range to 20th, just select it to the highest possible range that is not inclusive of the disabled ones:
so it'd select: firstly 2017-01-05 (as user selected) and then 2017-01-09 (last day that is not disabled)

Also there's some sort of graphical glitch that causes the selection css classes not to disappear, when clicking on the same selected dates twice (select any range, then deselect by clicking on the selected dates again, selection the range css will not disappear)

**Comment by kenneth-igaw** [comment]
Hi @pkly!

This issue are solved at [v1.4.8 version](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.4.8).

By default in `multiple: true` mode,

You can select only enabled dates.

If you select range what include disabled dates(disabledRanges, disabledDates, disabledWeekdays, minDate or maxDate etc), All select dates will be reset.

(`selectOver: true` option are escape this rule, Default value is `false`)

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
