### ISSUE TITLE
Set Monday as first day of week

### ISSUE THREAD

**Issue by quotetoxic** [KennethanCeyer/PIGNOSE-Calendar#26]
Hey, is it possible to make a Monday as a starting day of a week?

**Comment by KennethanCeyer** [comment]
Hmm

In current version,

Unfortunately, Setting to starting day feature are not supported.

But i list up this feature and will be updated within few days.

Thank you for asking!

**Comment by quotetoxic** [comment]
Thaks a lot!

**Comment by KennethanCeyer** [comment]
Hello @quotetoxic.

Recently, `[1.4.4`](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.4.4) version are updated.

In this version, `week` option are give `Starting day of week` by the number (0 is Sunday ~ 6 is Saturday).

EX) week: 1 means Monday first

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
