### ISSUE TITLE
Added new light-blue theme and update icons fonts 

### ISSUE THREAD

**Issue by adrian2monk** [KennethanCeyer/PIGNOSE-Calendar#27]
Hey guys, I recently added some new features on my [fork](https://github.com/adrian2monk/PIGNOSE-Calendar.git) for its awesome calendar plugin. I hope that you are interesting in its. In other branch [buggy](https://github.com/adrian2monk/PIGNOSE-Calendar/tree/buggy), I also added some simple events support features used in my own project. Happy to help in any other matter!!

**Comment by KennethanCeyer** [comment]
Hi @adrian2monk again!

I'm checking changes source code between origin and [this branch](https://github.com/adrian2monk/PIGNOSE-Calendar/tree/buggy).

I will reply soon.

Thank you 😄

**Comment by KennethanCeyer** [comment]
Oh your contribution activity is so nice.

I think navigation arrow icon is trouble things.

You give a solution to use icon fonts 👍 

But this solution isn't seem the ultimate solution (Ultimately, user can use this library only import CSS, JS files.)

We will must find better solution 🚨 

----

I think you effort to change this plugin to better so much.

I think i can merge your commit to origin master branch, But few source code needs a trim.

Thank you for your working @adrian2monk

**Comment by KennethanCeyer** [comment]
I was fetch new version [`v1.4.4`](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.4.4).

And this version are merge your `buggy`'s features. (Theme, Bower Settings, Events calendar etc.)

Thank you again for your contributing, It was very helpful 👍

**Comment by KennethanCeyer** [comment]
If you have any question just comment on this issue.

But this issue will be close after 3 days, If no have any questions.

**Comment by adrian2monk** [comment]
Thanks for your quick response and feedback! I think that yours comments are appreciate, if you want, I can create a new branch that restore the icons source to its previous version, if this is an issue or not a better solution. 

One of the things that I think could be a problem, was related with this icons loaded as background and either one way or another still having to import and find the correct path on css for image folder or fonts. For this reason, I think that svg and the other formats could be great for rendering and color change in other theme creation that will came in the future. Also, I added some new tasks in the Gruntfile for coping the fonts to dist folder and css rewrite previous to minifying the final build. In addition to this, I tweak a little the bower.json file to expose this main files when the component are pulled with bower.

I appreciate any comment about this topic, to the best of my knowledge this is what I think could be an improvement. I be glad if I can help to grow this feature and, as a side effect, I learn and meet people that help me to make myself a better js programmer.

Please, just post me what are the directive to follow to find a better improvement for this feature and I'll do it, count on it!

Best regards guys!!

**Comment by KennethanCeyer** [comment]
First of all, Changing navigation image to font icon is good think and i like it.

----

I was checking your updates on lunch time and surprised what you did.

Your buggy branch have many changes from origin.

Expected updates spec like this.

- Bower settings modified
- Grunt task added
- Core javascript changes (Bugs solved, Events feature added, Version and Modifier update)
- CSS Changes (font-size, SVG icon font, new theme)
- Doc Changes (Events, Theme docs)

----

In my opinion you did your best,

This plugin's core javascript is a complex and some difficult,

I'm sorry about i don't make any documents and wiki for contributors.

----

By the way

Honestly,  This plugin has many weeknesses by comparison with other modern plugins.

1. Unit Test and Coverage must be supported.

 In my plan, I will give [TravisCI](https://travis-ci.org/) and [CodeCov](https://codecov.io/) for automation testing and code safety.

 Test code will be made by *mocha* and use *istanbul* coverage tool.

2. The absence of AMD, RequireJS spec.

 Many javascript developer uses bundling like(Webpack, Rollup.js, SystemJS) and many modern library follows AMD and RequireJS module spec, This plugin must support AMD, RequireJS sepc.

3. Input datepicker

 Yes, This plugin support *Input type* datepicker, But only modal.
 
 But many business services are still using inline type datepicker.

 This plugin must gives inline type datepicker(below of the input).

4. Timepicker

 There are not many datepicker plugins that support timepicker.

 I hope to support it as well.

**Comment by adrian2monk** [comment]
Wow I'm impress and I like what I see. I'm working on Angular 1 project and my integrations already done for this project. I agree with you in this so many improvement that could be added to this feature. I will working on some of this. I'm really like to become this feature in one of my personal projects, I think that by this means could be learn a lot and be a better coder. Thanks again, I'm count on me for improve this feature and continuing making change and integration. 

--------------------------------------------------------------------------------------------------

Let's started with the top one issues of you your TODO list:

- [Unit Test and Coverage must be supported] 
- [The absence of AMD, RequireJS spec.]

Also, the [TravisCI](https://travis-ci.org/), [CodeCov](https://codecov.io/), [mocha](https://mochajs.org/) and [istanbul](https://github.com/gotwarlost/istanbul) is a great thing, some of which even know it (**CodeCov** & **istanbul**). I could help with this dev tasks and I be glad to collaborate with you! 

Thanks a lot and wait for future pull requests ;) @KennethanCeyer 

PD: If you want to share any thoughts, this is my google account adrian2monk too, send me an invitation on hangouts :+1:

**Comment by KennethanCeyer** [comment]
I'm very glad to hear for your motivation.

From now on, I have a time to improve this project. 📆 

And @adrian2monk, I think you have an enough skills to contribute this project.

----

So, firstly we need to set a `Milestone` to approach our goal.

I will arrange orders by priority of the tasks:
(Few tasks are added)

0. Documentation * Continuous task

1. Sass or Less support
2. Unit Test and Coverage
3. Asynchronous Dynamic Creation
4. The absence of AMD, RequireJS spec
5. Input datepicker
6. Timepicker
7. Integration

----

We will use GitHub Project for management of this project.

I list upped those task on [here]

**Comment by KennethanCeyer** [comment]
[v1.4.7 version](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.4.7) are support AMD, CommonJS module type.

This version has changed many source structures.

We are not using `vender` folder anymore.

`$.fn.pignseCalendar` gives function style.

like follows:

```javascript
var someElement = ...;
var pignoseCalendar = require('dist/js/pignose.calendar.js'); // CommonJS style.
pignoseCalendar(someElement, {
    // Options
});
```

or

```javascript
var someElement = ...;
define(['src/js/main', function(pignoseCalendar) {
    pignoseCalendar(someElement, {
        // Options
    });
});
```

This patterns help to make unit test.

(CommonJS style * NodeJS factory are built to `window`, `document` mocked by `jsdom`.

**Comment by adrian2monk** [comment]
I think that we already can close this issue and keep working on this tasks. By the way, I start with sass support on this weekend. Maybe my Angular 1.x directive helps to start integrate some frameworks too. I will catch up on [gitter](https://gitter.im/KennethanCeyer/PIGNOSE)

**Comment by KennethanCeyer** [comment]
Okay thank you @adrian2monk!!

I can handle ReactJS, AngularJS 2's @Directive.

I will touch with hangout soon ✋
