### ISSUE TITLE
Enable / Disable weekdays

### ISSUE THREAD

**Issue by feldmarv** [KennethanCeyer/PIGNOSE-Calendar#3]
An other question about enabling and disabling dates. How is it possible to disable some weekdays for ever. For example always disable saturday and sunday.
disableWeekdays: [6,7]

best regards
feldmarv

**Comment by KennethanCeyer** [comment]
Hi @feldmarv~!

Thank you for send a issue.

I think it is quite important feature.

I will make the option exactly as what you said tonight.

Thank you.


Best regards

Kenneth.

**Comment by feldmarv** [comment]
sounds cool! Yes it is a highly appreciated feature.
Thanks you!

**Comment by KennethanCeyer** [comment]
`disabled

**Comment by KennethanCeyer** [comment]
This issue will be closed at tomorrow, If you don't have another issue about this topic.

**Comment by feldmarv** [comment]
seems to work nicely! thx
Disabled weekdays are not togglable right?

**Comment by KennethanCeyer** [comment]
Yes sure!

All `disabled` feature can prevent click actions
like toggle buttons, range pick, general pick even modal

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺

**Comment by Filipe-Pedro** [comment]
y
