### ISSUE TITLE
Bug in Helper:Format keys for caching

### ISSUE THREAD

**Issue by skulegirl** [KennethanCeyer/PIGNOSE-Calendar#30]
The keys generated for caching in the Helper:Format are not always unique. In particular, if you format a date like (2017-1-21) and then format (2017-12-1), the second appears as a cache hit on the first. (Key is '{0}-{1}-{2}2017121' for both.) This should be solvable by just using a '+' for the join when creating the cache key, e.g.

var key = format + args.join('+');

resulting in '{0}-{1}-{2}2017+1+21'  and ''{0}-{1}-{2}2017+12+1' as the two respective keys.

**Comment by KennethanCeyer** [comment]
@skulegirl 

Oh i see!

If you did not tell me, I would not have noticed the issue.

Thank you for your advice.

This issue will be fixed to the next version.

**Comment by KennethanCeyer** [comment]
Hi @skulegirl!

This issue is solved at the version `v1.4.13`.

Thank you again for reporting the issue. 👍

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
