### ISSUE TITLE
Problem with using multiple and disabledWeekdays

### ISSUE THREAD

**Issue by alu4216** [KennethanCeyer/PIGNOSE-Calendar#31]
Hi Guys! I have problem when I want to use multiple option and disable Weekdays. Specifically, when active both option, I can't select multiple day correctly. For instance, Having selecting one day, the second day of selected range disable de firts day selected. My code is next:

 $.ajax({
        type: "POST",
        url: "/Aparicion/GetDisabledDays",
        data: { id: $('#concepto_idtarifa').val() }
    }).done(function (data) {

        if (data != null) {

            Date.prototype.yyyymmdd = function () {
                var mm = this.getMonth() + 1;
                var dd = this.getDate();

                return [this.getFullYear(),
                        (mm > 9 ? '' : '0') + mm,
                        (dd > 9 ? '' : '0') + dd
                ].join('/');
            };

            $('.calendar').pignoseCalendar({
                disabledWeekdays: data,
                lang: 'es',
                multiple: false,
                format: 'DD-MM-YYYY',
                minDate: new Date().yyyymmdd(),
                select: onClickHandler
            });
        }

Thank you for the help!

**Comment by KennethanCeyer** [comment]
Uhh.. Umm.. Hi @alu4216 

For example, 

With the multiple option set to `true`,

Does the issue occur when I select the first day and select the second day that over the disabled day?

I think this issue is related #25

**Comment by KennethanCeyer** [comment]
try `selectOver` option to `true`

**Comment by alu4216** [comment]
Hi @KennethanCeyer , 
With the option "selectorover" set to true, my problems was fixed, but, a new problem appears.

In the init of calendar, when click in a date firt time, the result is like if was a second click, and selected from the current day to the selected day. For example,I open the view and selected in the pignose calendar a day. today is 12/12/2017 and I click in 16/12/2017. The result is the days between this dates. I hope I have explained with clarify about my problem. 

Thank a lot  for your help!

**Comment by KennethanCeyer** [comment]
Hi @alu4216!

pignoseCalendar doesn't not provided any information

what is enable dates of date ranges.

you have to find enabled dates of the selected date range.

However i updated `select` callback.

Now you can take the information of enabled and disabled dates.

Check following codes.

```javascript
$('.calendar').pignoseCalendar({
    select: function(date, context) {
        var dateInfo = context.date;
        console.log('all date', dateInfo.all);
        console.log('enabled date', dateInfo.enabled);
        console.log('disabled date', dateInfo.disabled);
    },
    multiple: true,
    selectOver: true,
    disabledWeekdays: [0, 6]
});
```

If you select `2017-04-20` ~ `2017-04-28` range.

The output will returned like below.

```javascript
all date [
[moment object] 2017-04-20,
[moment object] 2017-04-21,
[moment object] 2017-04-22,
[moment object] 2017-04-23,
[moment object] 2017-04-24,
[moment object] 2017-04-25,
[moment object] 2017-04-26,
[moment object] 2017-04-27,
[moment object] 2017-04-28
]

enabled date [
[moment object] 2017-04-20,
[moment object] 2017-04-21,
[moment object] 2017-04-24,
[moment object] 2017-04-25,
[moment object] 2017-04-26,
[moment object] 2017-04-27,
[moment object] 2017-04-28
]
```

disabled date [
[moment object] 2017-04-22,
[moment object] 2017-04-23
]
```

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
