### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by lerendier** [KennethanCeyer/PIGNOSE-Calendar#33]
Hi,
The week option works with 0 and 1 only (for me)

**Comment by KennethanCeyer** [comment]
Hi @lerendier 

Do you want to disable days except 0 and 1 day of weeks?

I'm sorry, but I'd like to ask you a little more detailed questions.

Thank you!

**Comment by lerendier** [comment]
Hi,
thank you for contacting me. I would like the week to start on Saturday. I tried the option week: 6 but it does not work (same problem with the other days except 0 and 1; names of  days are displayed in the right order, but the days do not display. Thank you in advance for your answer.
Your Calendar is really beautiful!

**Comment by masivuyecokile** [comment]
@lerendier I think u can only Monday/Sunday can be the first day of the week. with `week:0` or `week:1`

**Comment by KennethanCeyer** [comment]
Hi @lerendier 

I will check this issue right now.

I'm sorry about late reply!!

**Comment by KennethanCeyer** [comment]
@lerendier 

This seem be an issue about reference negative index. (core issue)

I fixed the issue at `v1.4.13`.

Thank you for reporting 👍

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
