### ISSUE TITLE
German Language Support

### ISSUE THREAD

**Issue by feldmarv** [KennethanCeyer/PIGNOSE-Calendar#4]
Some adjustments for german language support:

In title: 
Deutsche -> Deutsch

Weekdays on the calendar:
MON -> MO
DIE -> DI
MIT -> MI
DON -> DO
FRE -> FR
SAM -> SA
SON -> SO

SAM and SON (SA, SO)  should be **red marked** not SON and MON

![bildschirmfoto 2016-11-02 um 20 59 54](https://cloud.githubusercontent.com/assets/9105618/19945280/c4a39368-a13f-11e6-94b2-00457595eb4a.png)

**Comment by KennethanCeyer** [comment]
Thank you for your advisement.

And sorry about late about delay to update.

It will be updated `today`.

Thank you mate @feldmarv

**Comment by KennethanCeyer** [comment]
This request be applied and fixed at https://github.com/KennethanCeyer/PIGNOSE-Calendar/commit/0723b9631399c5badec0a68cfed376c6c20edce6

You can see the fix at higher version than `v1.2.12`.

**Comment by KennethanCeyer** [comment]
This issue will be closed at tomorrow, If you don't have another issue about this topic.

**Comment by KennethanCeyer** [comment]
Anyway, I am very appreciated your advice.

So i will add you into contributors/language category of readme file at next update.

Thank you buddy!

**Comment by feldmarv** [comment]
Thank you for your fast implementations! Why is MO and SO red marked? I think red are the weekends so weekends are SA and SO.

all the best
Marvin

**Comment by KennethanCeyer** [comment]
Haha this is my mistake, Sorry 😄 

But hotfix has been updated at [v1.2.14](https://github.com/KennethanCeyer/PIGNOSE-Calendar/commit/23bed396712d5b2e366abd5bd0883f372a5392b5) version, and also now you can see [demo](http://www.pigno.se/barn/PIGNOSE-Calendar/)

**Comment by feldmarv** [comment]
great work! thank you

**Comment by KennethanCeyer** [comment]
This issue will be closed tonight.

If you have another issue, Please create new issue 🍺

**Comment by feldmarv** [comment]
Just found other wrong german translations

Jänner -> Januar
Feber -> Februar
