### ISSUE TITLE
Show events without click

### ISSUE THREAD

**Issue by matheusdelima** [KennethanCeyer/PIGNOSE-Calendar#5]
Hi, I'm using the Calendar for show events but,
I need a way to signal visually in calendar when have event without click on the day.

See exemple:

![captura de tela 2016-11-03 as 10 27 11](https://cloud.githubusercontent.com/assets/5695569/19967686/3137fea4-a1b0-11e6-8fe8-c8f5bf78898e.png)

**Thank you !**

**Comment by KennethanCeyer** [comment]
Hi @matheusdelima!

I'm understand what you need.

Umm, In your image, 6, 7, 8, 9, 10, 11 days be seemed to disabled days.

You can make disabled days by `disabledDays` option.

But the point seemed custom highlight days.

If you want put on the class at 3 day or 25 day(random picked),

and styling with CSS at those class, I think you can solve the issue.

If this solution is right, Please answer me i will make the feature on next version.

Sorry about the sentence, I am not living in English-speaking countries.

**Comment by matheusdelima** [comment]
Hi, Thanks for replay,
Basically the function `disabledDays` but in inverse.

I need only to specify the days there are events and no the days wich not events

You understand?

**Comment by KennethanCeyer** [comment]
This plugin give two options to give disable option for dates

`disabledDates`, `enabledDates`

If you only want to give some enable dates options.

You can use `enabledDates` (This is string array time and string format must be 'YYYY-MM-DD')

**Comment by matheusdelima** [comment]
Thank you! Great Job
