### ISSUE TITLE
Enable Support PT-BR

### ISSUE THREAD

**Issue by matheusdelima** [KennethanCeyer/PIGNOSE-Calendar#6]
Hi, i add support for Language PT-BR,
[This is link](https://github.com/matheusdelima/PIGNOSE-Calendar);

**Comment by KennethanCeyer** [comment]
@matheusdelima 

Hi i will update within one hour (I am solving another plugin issue).

And your nickname will be added to readme as contributors/languages, If you are okay.

Thank you for your supporting 👍

**Comment by matheusdelima** [comment]
Ok, Great :)

**Comment by KennethanCeyer** [comment]
This issue has been solved. 😄
