### ISSUE TITLE
Past Dates to Grey Out

### ISSUE THREAD

**Issue by snapp33** [KennethanCeyer/PIGNOSE-Calendar#7]
Is there a way to not able to click previous days before today (minDate)? If so please show, thanks!

**Comment by KennethanCeyer** [comment]
Hello @snapp33!

The answer is "Not yet"

But i will update at this time. so please wait few moment :octocat:

**Comment by KennethanCeyer** [comment]
Hi @snapp33 again!

You can set disabled date range by `minDate` and `maxDate` options.

This feature are added at v1.2.14 version, and now you can see demo at [here](http://www.pigno.se/barn/PIGNOSE-Calendar/)

Thank you 😄

**Comment by snapp33** [comment]
Thanks for being so quick Kennethan, I will have our tech person check it, thank you again!

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
