### ISSUE TITLE
Weekdays not disabling as I Chosen.. Please help?

### ISSUE THREAD

**Issue by daranaveen007** [KennethanCeyer/PIGNOSE-Calendar#8]
`$('.input-calendar').pignoseCalendar({
				format:"DD-MM-YYYY",
				buttons: false,
				multiple: true,
				disabledWeekdays: [0,3,6],
				select: onClickHandler
			});`

**Comment by KennethanCeyer** [comment]
Hi @daranaveen007 😄 

![Comfirm](http://www.nhpcw.com/upload/sample_calendar_110416084157.png)

I think this is working in my computer (Chrome)

The darkness button in range is disabled type buttons.

If you think this is problem, You can change disable style by override style sheet file.

----

**If you had occurred an error or got other problems,**

Please send me error logs on your console, and browser information.

I will fix your problem immediately.

**Comment by daranaveen007** [comment]
Oh!! Very much thankful to you sir @KennethanCeyer I got it now.. Thanks for the quick response..

**Comment by daranaveen007** [comment]
Thanks again.. You have gave me a precious thing to do something AWESOME..
