### ISSUE TITLE
German Language Support months

### ISSUE THREAD

**Issue by feldmarv** [KennethanCeyer/PIGNOSE-Calendar#9]
Just found other wrong german translations

Jänner -> Januar
Feber -> Februar

**Comment by KennethanCeyer** [comment]
Hi @feldmarv 

Thank you 😄 

You are very thoughtful.

It was reflected in version [v1.2.15](https://github.com/KennethanCeyer/PIGNOSE-Calendar/releases/tag/v1.2.15)!

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
